### ISSUE TITLE
pod install failing when using aggregate targets in xcode

### ISSUE THREAD

**Issue by rymir** [Instabug/Instabug-iOS#14]
when having an aggregate target in xcode, in this case the `test` aggregate target, pod install fails with:

```
-> Installing Instabug (3.23)
 > Git download
 > Git download
     $ /usr/local/bin/git clone https://github.com/Instabug/Instabug-iOS.git /Users/tex/Projects/Expend/workspace/temp/Pods/Instabug --single-branch --depth 1 --branch 3.23
     Cloning into '/Users/tex/Projects/Expend/workspace/temp/Pods/Instabug'...
     Note: checking out 'da8133102d75aa08fcd6b379c9e5376deb950e23'.

     You are in 'detached HEAD' state. You can look around, make experimental
     changes and commit them, and you can discard any commits you make in this
     state without impacting any branches by performing another checkout.

     If you want to create a new branch to retain commits you create, you may
     do so (now or later) by using -b with the checkout command again. Example:

       git checkout -b new_branch_name

 > Running prepare command
   $ /bin/bash  set -e ruby add_instabug_build_script.rb
   add_instabug_build_script.rb:24:in `block in <main>': undefined method `product_type' for <PBXAggregateTarget name=`test` UUID=`CFAAE2081A9B86D1002520B1`>:Xcodeproj::Project::Object::PBXAggregateTarget (NoMethodError)
   	from add_instabug_build_script.rb:23:in `each'
   	from add_instabug_build_script.rb:23:in `<main>'
[!] /bin/bash
set -e
ruby add_instabug_build_script.rb

add_instabug_build_script.rb:24:in `block in <main>': undefined method `product_type' for <PBXAggregateTarget name=`test` UUID=`CFAAE2081A9B86D1002520B1`>:Xcodeproj::Project::Object::PBXAggregateTarget (NoMethodError)

	from add_instabug_build_script.rb:23:in `each'

	from add_instabug_build_script.rb:23:in `<main>'
```

**Comment by msoliman** [comment]
The way to fix this is to use
```
pod 'Instabug', :git => 'https://github.com/Instabug/Instabug-iOS.git', :branch => 'no_build_script' 
```
instead of 
```
pod 'Instabug'
```
in your Podfile.

And in this case you'll have to add this build script manually into your app target:
```
SKIP_SIMULATOR_BUILDS=1
SCRIPT_SRC=$(find "$PROJECT_DIR" -name 'Instabug_dsym_upload.sh')
if [ ! "${SCRIPT_SRC}" ]; then
    echo "Instabug: err: script not found. Make sure that you're including Instabug.bundle in your project directory"
    exit 1
fi
source "${SCRIPT_SRC}"
```

**Comment by Arvkon** [comment]
Thanks a lot =)
